b=set()
a1=int(input("enter a Unique Number"))
b.add(a1)
a2=int(input("enter a Unique Number"))
b.add(a2)
a3=int(input("enter a Unique Number"))
b.add(a3)
a4=int(input("enter a Unique Number"))
b.add(a4)
a5=int(input("enter a Unique Number"))
b.add(a5)

print(b)
print(type(b))